const categories = {
  "Food and Drinks": ["Bar", "Cafe", "Groceries", "Restaurant", "Fast-Food"],
  Shopping: [
    "Cloths and Shoes",
    "Pharmacy",
    "Electronics and Accessories",
    "Gifts and Toys",
    "Health and Beauty",
    "Home and Garden",
    "Jewels and Accessories",
    "Kids",
    "Pets and Animals",
    "Stationery and Tools",
  ],
  Housing: [
    "Energy and Utilities",
    "Maintenance and Repairs",
    "Mortgage",
    "Property Insurance",
    "Rent",
    "Services",
  ],
  Transportation: [
    "Business Trips",
    "Long Distance",
    "Public Transport",
    "Taxi",
  ],
  Vehicle: [
    "Fuel",
    "Leasing",
    "Parking",
    "Rentals",
    "Vehicle Insurance",
    "Vehicle Maintenance",
  ],
  "Life and Entertainment": [
    "Active Sport and Fitness",
    "Alcohol and Tobacco",
    "Books Audio Subscriptions",
    "Charity and Gifts",
    "Culture Sport Events",
    "Eduction Development",
    "Healthcare",
    "Hobbies",
    "Doctor Fee",
    "Holiday Trips Hotels",
    "Life Events",
    "Lottery and Gambling",
    "TV and Streaming",
    "Wellness and Beauty",
  ],
  "Communication and Computers": [
    "Internet",
    "Phone",
    "Postal Services",
    "Software Apps Games",
  ],
  "Financial Expenses": [
    "Advisory",
    "Charges Fees",
    "Child Support",
    "Fines",
    "Insurance",
    "Loan Interest",
    "Taxes",
  ],
  Investment: [
    "Collections",
    "Financial Investments",
    "Realty",
    "Savings",
    "Vehicle Chattels",
  ],
  Income: [
    "Checks Coupons",
    "Child Support",
    "Dues and Grants",
    "Gifts",
    "Interests and Dividends",
    "Lending and Renting",
    "Lottery and Gambling",
    "Refunded Tax Purchases",
    "Rental Income",
    "Sale",
    "Wage and Invoices",
  ],
  Other: [],
};

export default categories;
